-- GENERATED BY DEFAULT (not ALWAYS) so V3's seed migration can insert explicit
-- ids without needing OVERRIDING SYSTEM VALUE, while runtime inserts still get
-- an auto-generated id when none is supplied.
CREATE TABLE specialty (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50)  NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uq_specialty_code UNIQUE (code)
);

CREATE TABLE doctor (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200) NOT NULL,
    specialty_id BIGINT       NOT NULL REFERENCES specialty (id),
    active       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_doctor_specialty_id ON doctor (specialty_id);

CREATE TABLE room (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(100) NOT NULL,
    active BOOLEAN      NOT NULL DEFAULT TRUE
);
